# Generated by Django 5.2.15 on 2026-06-23 22:28

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('operation_type'), name='unique_operation_type_ci')],
            },
        ),
        migrations.CreateModel(
            name='OperationInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('detail', models.TextField(blank=True, max_length=500)),
                ('in_room_time', models.TimeField(blank=True, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('elapsed_time', models.IntegerField(blank=True, null=True)),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timer.operationtype')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='unique_step_title_ci')],
            },
        ),
        migrations.CreateModel(
            name='StepInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('elapsed_time', models.IntegerField(blank=True, null=True)),
                ('operation_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='timer.operationinstance')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='timer.step')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Surgeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('first_name'), django.db.models.functions.text.Lower('last_name'), name='unique_surgeon_name_ci')],
            },
        ),
        migrations.AddField(
            model_name='operationinstance',
            name='surgeon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timer.surgeon'),
        ),
    ]
